name: Main

on:
  push:
    branches:
      - main
      - master
      - Version-v*
      - trigger-ci*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches-ignore:
      - master
  merge_group:
  schedule:
    # Run the full suite "overnight," once every half hour from 1:00am UTC until 2:59am UTC.
    # This helps with "Top 10 failed tests on the metamask-extension repository main branch,"
    # especially the Monday morning list, which is otherwise usually a fake empty.
    - cron: '0,30 1-2 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !(contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/heads/master')) }}

env:
  # For a `pull_request` event, the branch is `github.head_ref``.
  # For a `push` event, the branch is `github.ref_name`.
  BRANCH: ${{ github.head_ref || github.ref_name }}
  # For a `pull_request` event, the fork is `github.event.pull_request.head.repo.fork`.
  # For a `push` event, the fork is `github.event.repository.fork`.
  IS_FORK: ${{ github.event.pull_request.head.repo.fork || github.event.repository.fork }}

permissions:
  contents: write # required for releases
  id-token: write # required for s3 uploads

jobs:
  prep-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          cache-node-modules: true
          skip-allow-scripts: true
          yarn-custom-url: ${{ vars.YARN_URL }}

  run-benchmarks:
    uses: ./.github/workflows/run-benchmarks.yml
    needs:
      - prep-deps
